Repository fylein/fyle-integrations-app-e2e-tests, pull requests merged in 2025-06, with the labels that each got.

#5 feat: add fyle account setup, remove playwright boilerplate
  .gitignore
  common/fixture.ts
  common/setup/fyle-account.ts
  common/setup/login.ts
  common/utils/api.ts
  common/utils/get-super-admin-access-token.ts
  common/utils/wait.ts
  global-setup.ts
  package-lock.json
  package.json
  tests-examples/demo-todo-app.spec.ts
  tests/example.spec.ts
Labels: size/XL

#7 ci: fix eol and outdated JS scan action
  .github/workflows/eol-outdated-js-scan.yml
Labels: size/XS

#9 ci: fix the failure message for the PR title check
  .github/pr-checks-config.yml
Labels: size/XS

#6 feat: add e2e test for intacct, test onboarding
  .gitignore
  common/utils/wait.ts
  e2e/intacct.spec.ts
  playwright.config.ts
Labels: size/M

#8 ci: write a workflow to schedule e2e tests daily
  .github/workflows/playwright.yml
  playwright.config.ts
Labels: size/S

#10 feat: add service files to create Fyle reports via platform API
  common/setup/corporate-card.service.ts
  common/setup/expenses.service.ts
  common/setup/org-settings.service.ts
  common/setup/reports.service.ts
  eslint.config.mjs
Labels: size/L

#18 feat: assert and resolve intacct errors
  e2e/intacct.spec.ts
Labels: size/S

#22 chore: remove eol action
  .github/workflows/eol-outdated-js-scan.yml
Labels: size/S
